export getAdsBlocked from './passive/getAdsBlocked.js';
export getColourDepth from './passive/getColourDepth.js';
export getCookiesEnabled from './passive/getCookiesEnabled.js';
export getDoNotTrack from './passive/getDoNotTrack.js';
export getLocalStorageEnabled from './passive/getLocalStorageEnabled.js';
export getNavigatorProperties from './passive/getNavigatorProperties.js';
export getPlatform from './passive/getPlatform.js';
export getScreenResolution from './passive/getScreenResolution.js';
export getTimezone from './passive/getTimezone.js';
