export getAdsBlocked from './passive/getAdsBlocked';
export getColourDepth from './passive/getColourDepth';
export getCookiesEnabled from './passive/getCookiesEnabled';
export getDoNotTrack from './passive/getDoNotTrack';
export getLocalStorageEnabled from './passive/getLocalStorageEnabled';
export getNavigatorProperties from './passive/getNavigatorProperties';
export getPlatform from './passive/getPlatform';
export getScreenResolution from './passive/getScreenResolution';
export getTimezone from './passive/getTimezone';
